dionysos-dev/Dionysos.jl

- src/abstraction.jl
- src/gridspace.jl
- src/subset.jl
- src/symbolicmodel.jl
- test/test_symbolicmodel.jl
Using Julia v1.5, before this PR:
```julia
julia> PathPlanning.PathPlanning.path_planning(4.0, nsteps = 100)
set_symmodel_from_controlsystem! started
Computing symbolic control system: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Time: 0:00:03
set_symmodel_from_controlsystem! terminated with success: 11839413 transitions created
3.736904 seconds (1.18 M allocations: 587.030 MiB, 3.03% gc time)
set_controller_reach! started
set_controller_reach! terminated with success
4.888495 seconds (1.33 k allocations: 142.315 MiB, 0.69% gc time)
```
After this PR:
```julia
julia> PathPlanning.PathPlanning.path_planning(4.0, nsteps = 100) …
```
> Add CellRef

- src/controller.jl
- src/controlsystem.jl
- src/symbolicmodel.jl
Il y a du avoir un "problème" avec le merge avec la branch "controller-safe" parce que je ne vois pas les changements
> Controller-safe + comments Vectors vs Sets

- Project.toml
> Add my name

- Project.toml
- src/BDD/BDD.jl
- src/BDD/BitSet.jl
- src/Dionysos.jl
- test/BDD/BDD.jl
- test/runtests.jl
I've started with a set of `Int` to start simple, the next step is the set of `NTuple{N, Int}`
> Add BDD.BitSet

- Project.toml
- examples/gol_lazar_belta.jl
- src/Dionysos.jl
- src/bemporad_morari.jl
- src/optimal_control.jl
- test/gol_lazar_belta.jl
- test/runtests.jl
- test/solvers.jl
Implements algorithm of
Bemporad, Alberto, and Manfred Morari. "Control of systems integrating logic, dynamics, and constraints." Automatica 35.3 (1999): 407-427.
and test it on the example of
Gol, Ebru Aydin, Mircea Lazar, and Calin Belta. "Temporal logic model predictive control." Automatica 56 (2015): 78-85.
Bouchat, Jean, and Raphaël M. Jungers. Reinforcement learning for the optimal control of hybrid systems. Diss. MSc Thesis, UC Louvain, 2019.
> Add Bemporad_Morari algorithm

- .github/workflows/ci.yml
- src/Dionysos.jl
- src/bemporad_morari.jl
- src/branch_and_bound.jl
- src/optimal_control.jl
- src/q_learning.jl
- src/upstream.jl
- test/gol_lazar_belta.jl
- test/solvers.jl
- test/test_controllerreach.jl
- test/test_controllersafe.jl
- test/test_controlsystemgrowth.jl
- test/test_controlsystemlinearized.jl
- test/test_fromcontrolsystemgrowth.jl
- test/test_fromcontrolsystemlinearized.jl
- test/test_griddomain.jl
It gives more flexibility to get more info after the solve and also allow to resolve with modifications with, e.g. only `x_0`
> Refactor Algorithms to Optimizer

- docs/src/examples/Gol, Lazar & Belta (2013).jl
- examples/gol_lazar_belta.jl
- src/bemporad_morari.jl
- src/branch_and_bound.jl
- src/q_learning.jl
- test/gol_lazar_belta.jl
- test/solvers.jl
Allows to use solvers or polyhedra library of other coefficient types such as `BigFloat`
> Generalize code to work with any coefficient type

- Project.toml
- src/Dionysos.jl
The issues with CUDD was fixed in https://github.com/sisl/CUDD.jl/pull/17 so this PR add it back.
> Reenable CUDD

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- Project.toml
- docs/src/examples/Gol, Lazar & Belta (2013).jl
- requirements.txt
- src/bemporad_morari.jl
- src/branch_and_bound.jl
- src/q_learning.jl
- test/gol_lazar_belta.jl
Closes #93 
Closes #110 
Closes #112
> Update to JuMP v0.23

- Project.toml
Closes https://github.com/dionysos-dev/Dionysos.jl/pull/118
> Remove Symbolics from deps

- docs/src/examples/Gol, Lazar & Belta (2013).jl
- examples/example_SF_abst_2.jl
- problems/GolLazarBelta.jl
- problems/PWAsys.jl
- problems/PathPlanning.jl
- problems/robot_problem.jl
- src/control/optimal_control.jl
- src/problem/optim/bemporad_morari.jl
- src/problem/optim/branch_and_bound.jl
- src/problem/optim/q_learning.jl
- src/problem/problem.jl
I rewrote ``OptimalControlProblem`` and ``SafetyProblem`` to be more general.
> general problems created (Opt and Safety)

- Project.toml
Closes https://github.com/dionysos-dev/Dionysos.jl/issues/124
> Remove Symbolics dependency

- docs/src/developers/git.md
- docs/src/developers/setup.md
Preview https://dionysos-dev.github.io/Dionysos.jl/previews/PR178/
> Improve Git and Set up documention

- src/domain/nested_domain.jl
- src/symbolic/lazy_symbolic.jl
- src/symbolic/nested_symbolic.jl
This now gives warnings during precompilation with Julia v1.8
> Remove unused type arguments

- docs/src/examples/Path planning.jl
- problems/PathPlanning.jl
- src/problem/optim/abstraction.jl
- src/problem/problem.jl
Preview https://dionysos-dev.github.io/Dionysos.jl/previews/PR176/
> Add Abstraction solver

- docs/src/developers/setup.md
Preview https://dionysos-dev.github.io/Dionysos.jl/previews/PR188
> Add "@" to a link

- docs/src/examples/DC-DC converter.jl
- problems/DCDC.jl
- src/problem/optim/abstraction.jl
Preview https://dionysos-dev.github.io/Dionysos.jl/previews/PR189
> Use Abstraction.Optimizer for DC-DC example

- docs/src/developers/setup.md
- src/domain/domain.jl
- src/domain/grid.jl
- src/problem/optim/abstraction.jl
Closes https://github.com/dionysos-dev/Dionysos.jl/issues/187
> Add new INCL_MODE with centers for input

- examples/example_SF_abst_1.jl
- examples/example_ellipsoid.jl
- src/utils/ellipsoid.jl
- test/runtests.jl
- test/symbolic/test_automaton.jl
- test/utils/data_structures/tree.jl
- test/utils/ellipsoid.jl
- test/utils/rectangle.jl
I added tests for ellipsoid.jl and RRT.jl
> add test for ellipsoid and RRT

- examples/SFRRT/example_lazy_ellipsoid_1.jl
- examples/SFRRT/examples.jl
- src/symbolic/ellipsoidal_transitions.jl
- src/utils/data_structures/tree.jl
- src/utils/search/RRT.jl
(cherry picked from commit 03ccbb5aaf79b2d6d97da199c82584c2f8c2ff22)
> add new LMIs

- examples/SFRRT/example_lazy_ellipsoid_1.jl
- src/problem/optim/abstraction.jl
- src/system/controlsystem.jl
- src/utils/data_structures/tree.jl
- clean the variables/parameters
- add parameters into the optimizer
> Sfrrt LMIs

- bench/Project.toml
- bench/benchmark.jl
- problems/GolLazarBelta.jl
- problems/PWAsys.jl
- src/problem/optim/bemporad_morari.jl
- src/problem/problem.jl
Closes https://github.com/dionysos-dev/Dionysos.jl/issues/126
> Add benchmark

- docs/src/examples/Ellipsoids.jl
- docs/src/examples/Grid.jl
Solves https://github.com/dionysos-dev/Dionysos.jl/issues/218
> Fix plots in Ellipsoids example + mini-changes of comments

- .github/workflows/documentation.yml
- requirements.txt
Might not be needed anymore now that use use recipes: https://github.com/dionysos-dev/Dionysos.jl/pull/224
> Remove python install from doc

- docs/src/reference/Optim.md
- docs/src/reference/Problem.md
- docs/src/reference/System.md
- src/optim/abstraction/SCOTS_abstraction.jl
- src/optim/abstraction/ellipsoids_abstraction.jl
- src/optim/abstraction/hierarchical_abstraction.jl
- src/optim/abstraction/lazy_abstraction.jl
- src/optim/abstraction/lazy_ellipsoids_abstraction.jl
- src/optim/bemporad_morari.jl
- src/optim/branch_and_bound.jl
- src/problem/problems.jl
Add solvers to the documentation
> Add Optim Docu

- test/runtests.jl
- test/utils/test_LazySetOperations.jl
Add tests for LazySetOperations.jl in Utils
> Finish improvement code covering

- BipedRobot/Project.toml
- BipedRobot/src/BipedRobot.jl
- BipedRobot/src/piracy.jl
- BipedRobot/test/runtests.jl
https://github.com/dionysos-dev/Dionysos.jl/pull/290#issuecomment-1715990640
> Move type piracy in BipedRobot package

- test/examples/test_gol_lazar_belta.jl
Should solve https://github.com/dionysos-dev/Dionysos.jl/issues/304
> Fix CI bug

- Project.toml
- bench/benchmark.jl
- docs/Project.toml
- docs/src/reference/Utils.md
- src/utils/utils.jl
- test/runtests.jl
To increase coverage before release
> Decomment BDD tests

- Project.toml
This reverts commit 21167e5f3b8fa0696868c36c5340db05f8d20283.
> v0.0.2 -> v0.0.1 (revert)

- .github/workflows/documentation.yml
Let's use the branch on the fork until https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/pull/135 is merged
For https://github.com/dionysos-dev/Dionysos.jl/issues/356
> Use radius branch of IntervalLinearAlgebra

- bench/benchmark_definitions.jl
`SCOTSAbstraction` -> `UniformGridAbstraction` after refactoring it
> Fix `bench/benchmark_definitions.jl`

- problems/simple_problem.jl
Implement @schillic comment from https://github.com/JuliaCon/proceedings-review/issues/160#issuecomment-2424899533
> Fix test warning 

- .github/workflows/BipedRobot.yml
- bench/benchmark_definitions.jl
- docs/src/examples/solvers/DC-DC converter.jl
- docs/src/examples/solvers/Path planning.jl
- problems/dc_dc.jl
- problems/path_planning.jl
- src/MOI_wrapper.jl
- src/optim/abstraction/uniform_grid_abstraction.jl
- src/system/controlsystem.jl
- test/optim/test_UniformGridAbstraction_reachability.jl
- test/optim/test_UniformGridAbstraction_safety.jl
This clearly separates solver attributes to descriptions of the control problem
> Move solver parameters to attributes

- .github/workflows/BipedRobot.yml
- BipedRobot/Project.toml
@ferrolho Thanks for fixing RigidBodyDynamics !
See https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/642
> BipedRobot back on Julia v1.11

- docs/src/examples/solvers/single pendulum reach.jl
[Preview](https://dionysos-dev.github.io/Dionysos.jl/previews/PR392/generated/single%20pendulum%20reach/)
> This is the single pendulum implemented into the new frame.

- docs/src/examples/solvers/single pendulum reach.jl
Preview https://dionysos-dev.github.io/Dionysos.jl/previews/PR394
> Cosmetic changes to single pendulum

- README.md
- Added the JCON paper badge
- Re-arranged a bit the badges
> Add JCON to README.md

- test/optim/test_ellipsoids_abstraction.jl
It was renamed in https://github.com/dionysos-dev/Dionysos.jl/pull/419
> Fix ellipsoid abstraction test

- src/system/controller.jl
> Remove extra SymbolicController definition
